export const countriesData = [
  { countryName: "Aruba", countryCapital: "Oranjestad" },
  { countryName: "Afghanistan", countryCapital: "Kabul" },
  { countryName: "Angola", countryCapital: "Luanda" },
  { countryName: "Anguilla", countryCapital: "The Valley" },
  { countryName: "Åland Islands", countryCapital: "Mariehamn" },
  { countryName: "Albania", countryCapital: "Tirana" },
  { countryName: "Andorra", countryCapital: "Andorra la Vella" },
  { countryName: "United Arab Emirates", countryCapital: "Abu Dhabi" },
  { countryName: "Argentina", countryCapital: "Buenos Aires" },
  { countryName: "Armenia", countryCapital: "Yerevan" },
  { countryName: "American Samoa", countryCapital: "Pago Pago" },
  {
    countryName: "French Southern and Antarctic Lands",
    countryCapital: "Port-aux-Français",
  },
  { countryName: "Antigua and Barbuda", countryCapital: "Saint John's" },
  { countryName: "Australia", countryCapital: "Canberra" },
  { countryName: "Austria", countryCapital: "Vienna" },
  { countryName: "Azerbaijan", countryCapital: "Baku" },
  { countryName: "Burundi", countryCapital: "Gitega" },
  { countryName: "Belgium", countryCapital: "Brussels" },
  { countryName: "Benin", countryCapital: "Porto-Novo" },
  { countryName: "Burkina Faso", countryCapital: "Ouagadougou" },
  { countryName: "Bangladesh", countryCapital: "Dhaka" },
  { countryName: "Bulgaria", countryCapital: "Sofia" },
  { countryName: "Bahrain", countryCapital: "Manama" },
  { countryName: "Bahamas", countryCapital: "Nassau" },
  { countryName: "Bosnia and Herzegovina", countryCapital: "Sarajevo" },
  { countryName: "Saint Barthélemy", countryCapital: "Gustavia" },
  {
    countryName: "Saint Helena, Ascension and Tristan da Cunha",
    countryCapital: "Jamestown",
  },
  { countryName: "Belarus", countryCapital: "Minsk" },
  { countryName: "Belize", countryCapital: "Belmopan" },
  { countryName: "Bermuda", countryCapital: "Hamilton" },
  { countryName: "Bolivia", countryCapital: "Sucre" },
  { countryName: "Caribbean Netherlands", countryCapital: "Kralendijk" },
  { countryName: "Brazil", countryCapital: "Brasília" },
  { countryName: "Barbados", countryCapital: "Bridgetown" },
  { countryName: "Brunei", countryCapital: "Bandar Seri Begawan" },
  { countryName: "Bhutan", countryCapital: "Thimphu" },
  { countryName: "Botswana", countryCapital: "Gaborone" },
  { countryName: "Central African Republic", countryCapital: "Bangui" },
  { countryName: "Canada", countryCapital: "Ottawa" },
  { countryName: "Cocos (Keeling) Islands", countryCapital: "West Island" },
  { countryName: "Switzerland", countryCapital: "Bern" },
  { countryName: "Chile", countryCapital: "Santiago" },
  { countryName: "China", countryCapital: "Beijing" },
  { countryName: "Ivory Coast", countryCapital: "Yamoussoukro" },
  { countryName: "Cameroon", countryCapital: "Yaoundé" },
  { countryName: "DR Congo", countryCapital: "Kinshasa" },
  { countryName: "Republic of the Congo", countryCapital: "Brazzaville" },
  { countryName: "Cook Islands", countryCapital: "Avarua" },
  { countryName: "Colombia", countryCapital: "Bogotá" },
  { countryName: "Comoros", countryCapital: "Moroni" },
  { countryName: "Cape Verde", countryCapital: "Praia" },
  { countryName: "Costa Rica", countryCapital: "San José" },
  { countryName: "Cuba", countryCapital: "Havana" },
  { countryName: "Curaçao", countryCapital: "Willemstad" },
  { countryName: "Christmas Island", countryCapital: "Flying Fish Cove" },
  { countryName: "Cayman Islands", countryCapital: "George Town" },
  { countryName: "Cyprus", countryCapital: "Nicosia" },
  { countryName: "Czechia", countryCapital: "Prague" },
  { countryName: "Germany", countryCapital: "Berlin" },
  { countryName: "Djibouti", countryCapital: "Djibouti" },
  { countryName: "Dominica", countryCapital: "Roseau" },
  { countryName: "Denmark", countryCapital: "Copenhagen" },
  { countryName: "Dominican Republic", countryCapital: "Santo Domingo" },
  { countryName: "Algeria", countryCapital: "Algiers" },
  { countryName: "Ecuador", countryCapital: "Quito" },
  { countryName: "Egypt", countryCapital: "Cairo" },
  { countryName: "Eritrea", countryCapital: "Asmara" },
  { countryName: "Western Sahara", countryCapital: "El Aaiún" },
  { countryName: "Spain", countryCapital: "Madrid" },
  { countryName: "Estonia", countryCapital: "Tallinn" },
  { countryName: "Ethiopia", countryCapital: "Addis Ababa" },
  { countryName: "Finland", countryCapital: "Helsinki" },
  { countryName: "Fiji", countryCapital: "Suva" },
  { countryName: "Falkland Islands", countryCapital: "Stanley" },
  { countryName: "France", countryCapital: "Paris" },
  { countryName: "Faroe Islands", countryCapital: "Tórshavn" },
  { countryName: "Micronesia", countryCapital: "Palikir" },
  { countryName: "Gabon", countryCapital: "Libreville" },
  { countryName: "United Kingdom", countryCapital: "London" },
  { countryName: "Georgia", countryCapital: "Tbilisi" },
  { countryName: "Guernsey", countryCapital: "St. Peter Port" },
  { countryName: "Ghana", countryCapital: "Accra" },
  { countryName: "Gibraltar", countryCapital: "Gibraltar" },
  { countryName: "Guinea", countryCapital: "Conakry" },
  { countryName: "Guadeloupe", countryCapital: "Basse-Terre" },
  { countryName: "Gambia", countryCapital: "Banjul" },
  { countryName: "Guinea-Bissau", countryCapital: "Bissau" },
  { countryName: "Equatorial Guinea", countryCapital: "Malabo" },
  { countryName: "Greece", countryCapital: "Athens" },
  { countryName: "Grenada", countryCapital: "St. George's" },
  { countryName: "Greenland", countryCapital: "Nuuk" },
  { countryName: "Guatemala", countryCapital: "Guatemala City" },
  { countryName: "French Guiana", countryCapital: "Cayenne" },
  { countryName: "Guam", countryCapital: "Hagåtña" },
  { countryName: "Guyana", countryCapital: "Georgetown" },
  { countryName: "Hong Kong", countryCapital: "City of Victoria" },
  { countryName: "Honduras", countryCapital: "Tegucigalpa" },
  { countryName: "Croatia", countryCapital: "Zagreb" },
  { countryName: "Haiti", countryCapital: "Port-au-Prince" },
  { countryName: "Hungary", countryCapital: "Budapest" },
  { countryName: "Indonesia", countryCapital: "Jakarta" },
  { countryName: "Isle of Man", countryCapital: "Douglas" },
  { countryName: "India", countryCapital: "New Delhi" },
  {
    countryName: "British Indian Ocean Territory",
    countryCapital: "Diego Garcia",
  },
  { countryName: "Ireland", countryCapital: "Dublin" },
  { countryName: "Iran", countryCapital: "Tehran" },
  { countryName: "Iraq", countryCapital: "Baghdad" },
  { countryName: "Iceland", countryCapital: "Reykjavik" },
  { countryName: "Israel", countryCapital: "Jerusalem" },
  { countryName: "Italy", countryCapital: "Rome" },
  { countryName: "Jamaica", countryCapital: "Kingston" },
  { countryName: "Jersey", countryCapital: "Saint Helier" },
  { countryName: "Jordan", countryCapital: "Amman" },
  { countryName: "Japan", countryCapital: "Tokyo" },
  { countryName: "Kazakhstan", countryCapital: "Nur-Sultan" },
  { countryName: "Kenya", countryCapital: "Nairobi" },
  { countryName: "Kyrgyzstan", countryCapital: "Bishkek" },
  { countryName: "Cambodia", countryCapital: "Phnom Penh" },
  { countryName: "Kiribati", countryCapital: "South Tarawa" },
  { countryName: "Saint Kitts and Nevis", countryCapital: "Basseterre" },
  { countryName: "South Korea", countryCapital: "Seoul" },
  { countryName: "Kosovo", countryCapital: "Pristina" },
  { countryName: "Kuwait", countryCapital: "Kuwait City" },
  { countryName: "Laos", countryCapital: "Vientiane" },
  { countryName: "Lebanon", countryCapital: "Beirut" },
  { countryName: "Liberia", countryCapital: "Monrovia" },
  { countryName: "Libya", countryCapital: "Tripoli" },
  { countryName: "Saint Lucia", countryCapital: "Castries" },
  { countryName: "Liechtenstein", countryCapital: "Vaduz" },
  { countryName: "Sri Lanka", countryCapital: "Sri Jayawardenepura Kotte" },
  { countryName: "Lesotho", countryCapital: "Maseru" },
  { countryName: "Lithuania", countryCapital: "Vilnius" },
  { countryName: "Luxembourg", countryCapital: "Luxembourg" },
  { countryName: "Latvia", countryCapital: "Riga" },
  { countryName: "Saint Martin", countryCapital: "Marigot" },
  { countryName: "Morocco", countryCapital: "Rabat" },
  { countryName: "Monaco", countryCapital: "Monaco" },
  { countryName: "Moldova", countryCapital: "Chișinău" },
  { countryName: "Madagascar", countryCapital: "Antananarivo" },
  { countryName: "Maldives", countryCapital: "Malé" },
  { countryName: "Mexico", countryCapital: "Mexico City" },
  { countryName: "Marshall Islands", countryCapital: "Majuro" },
  { countryName: "North Macedonia", countryCapital: "Skopje" },
  { countryName: "Mali", countryCapital: "Bamako" },
  { countryName: "Malta", countryCapital: "Valletta" },
  { countryName: "Myanmar", countryCapital: "Naypyidaw" },
  { countryName: "Montenegro", countryCapital: "Podgorica" },
  { countryName: "Mongolia", countryCapital: "Ulan Bator" },
  { countryName: "Northern Mariana Islands", countryCapital: "Saipan" },
  { countryName: "Mozambique", countryCapital: "Maputo" },
  { countryName: "Mauritania", countryCapital: "Nouakchott" },
  { countryName: "Montserrat", countryCapital: "Plymouth" },
  { countryName: "Martinique", countryCapital: "Fort-de-France" },
  { countryName: "Mauritius", countryCapital: "Port Louis" },
  { countryName: "Malawi", countryCapital: "Lilongwe" },
  { countryName: "Malaysia", countryCapital: "Kuala Lumpur" },
  { countryName: "Mayotte", countryCapital: "Mamoudzou" },
  { countryName: "Namibia", countryCapital: "Windhoek" },
  { countryName: "New Caledonia", countryCapital: "Nouméa" },
  { countryName: "Niger", countryCapital: "Niamey" },
  { countryName: "Norfolk Island", countryCapital: "Kingston" },
  { countryName: "Nigeria", countryCapital: "Abuja" },
  { countryName: "Nicaragua", countryCapital: "Managua" },
  { countryName: "Niue", countryCapital: "Alofi" },
  { countryName: "Netherlands", countryCapital: "Amsterdam" },
  { countryName: "Norway", countryCapital: "Oslo" },
  { countryName: "Nepal", countryCapital: "Kathmandu" },
  { countryName: "Nauru", countryCapital: "Yaren" },
  { countryName: "New Zealand", countryCapital: "Wellington" },
  { countryName: "Oman", countryCapital: "Muscat" },
  { countryName: "Pakistan", countryCapital: "Islamabad" },
  { countryName: "Panama", countryCapital: "Panama City" },
  { countryName: "Pitcairn Islands", countryCapital: "Adamstown" },
  { countryName: "Peru", countryCapital: "Lima" },
  { countryName: "Philippines", countryCapital: "Manila" },
  { countryName: "Palau", countryCapital: "Ngerulmud" },
  { countryName: "Papua New Guinea", countryCapital: "Port Moresby" },
  { countryName: "Poland", countryCapital: "Warsaw" },
  { countryName: "Puerto Rico", countryCapital: "San Juan" },
  { countryName: "North Korea", countryCapital: "Pyongyang" },
  { countryName: "Portugal", countryCapital: "Lisbon" },
  { countryName: "Paraguay", countryCapital: "Asunción" },
  { countryName: "French Polynesia", countryCapital: "Papeetē" },
  { countryName: "Qatar", countryCapital: "Doha" },
  { countryName: "Réunion", countryCapital: "Saint-Denis" },
  { countryName: "Romania", countryCapital: "Bucharest" },
  { countryName: "Russia", countryCapital: "Moscow" },
  { countryName: "Rwanda", countryCapital: "Kigali" },
  { countryName: "Saudi Arabia", countryCapital: "Riyadh" },
  { countryName: "Sudan", countryCapital: "Khartoum" },
  { countryName: "Senegal", countryCapital: "Dakar" },
  { countryName: "Singapore", countryCapital: "Singapore" },
  { countryName: "South Georgia", countryCapital: "King Edward Point" },
  { countryName: "Svalbard and Jan Mayen", countryCapital: "Longyearbyen" },
  { countryName: "Solomon Islands", countryCapital: "Honiara" },
  { countryName: "Sierra Leone", countryCapital: "Freetown" },
  { countryName: "El Salvador", countryCapital: "San Salvador" },
  { countryName: "San Marino", countryCapital: "City of San Marino" },
  { countryName: "Somalia", countryCapital: "Mogadishu" },
  { countryName: "Saint Pierre and Miquelon", countryCapital: "Saint-Pierre" },
  { countryName: "Serbia", countryCapital: "Belgrade" },
  { countryName: "South Sudan", countryCapital: "Juba" },
  { countryName: "São Tomé and Príncipe", countryCapital: "São Tomé" },
  { countryName: "Suriname", countryCapital: "Paramaribo" },
  { countryName: "Slovakia", countryCapital: "Bratislava" },
  { countryName: "Slovenia", countryCapital: "Ljubljana" },
  { countryName: "Sweden", countryCapital: "Stockholm" },
  { countryName: "Eswatini", countryCapital: "Mbabane" },
  { countryName: "Sint Maarten", countryCapital: "Philipsburg" },
  { countryName: "Seychelles", countryCapital: "Victoria" },
  { countryName: "Syria", countryCapital: "Damascus" },
  { countryName: "Turks and Caicos Islands", countryCapital: "Cockburn Town" },
  { countryName: "Chad", countryCapital: "N'Djamena" },
  { countryName: "Togo", countryCapital: "Lomé" },
  { countryName: "Thailand", countryCapital: "Bangkok" },
  { countryName: "Tajikistan", countryCapital: "Dushanbe" },
  { countryName: "Tokelau", countryCapital: "Fakaofo" },
  { countryName: "Turkmenistan", countryCapital: "Ashgabat" },
  { countryName: "Timor-Leste", countryCapital: "Dili" },
  { countryName: "Tonga", countryCapital: "Nuku'alofa" },
  { countryName: "Trinidad and Tobago", countryCapital: "Port of Spain" },
  { countryName: "Tunisia", countryCapital: "Tunis" },
  { countryName: "Turkey", countryCapital: "Ankara" },
  { countryName: "Tuvalu", countryCapital: "Funafuti" },
  { countryName: "Taiwan", countryCapital: "Taipei" },
  { countryName: "Tanzania", countryCapital: "Dodoma" },
  { countryName: "Uganda", countryCapital: "Kampala" },
  { countryName: "Ukraine", countryCapital: "Kyiv" },
  {
    countryName: "United States Minor Outlying Islands",
    countryCapital: "Washington DC",
  },
  { countryName: "Uruguay", countryCapital: "Montevideo" },
  { countryName: "United States", countryCapital: "Washington, D.C." },
  { countryName: "Uzbekistan", countryCapital: "Tashkent" },
  { countryName: "Vatican City", countryCapital: "Vatican City" },
  {
    countryName: "Saint Vincent and the Grenadines",
    countryCapital: "Kingstown",
  },
  { countryName: "Venezuela", countryCapital: "Caracas" },
  { countryName: "British Virgin Islands", countryCapital: "Road Town" },
  {
    countryName: "United States Virgin Islands",
    countryCapital: "Charlotte Amalie",
  },
  { countryName: "Vietnam", countryCapital: "Hanoi" },
  { countryName: "Vanuatu", countryCapital: "Port Vila" },
  { countryName: "Wallis and Futuna", countryCapital: "Mata-Utu" },
  { countryName: "Samoa", countryCapital: "Apia" },
  { countryName: "Yemen", countryCapital: "Sana'a" },
  { countryName: "Zambia", countryCapital: "Lusaka" },
  { countryName: "Zimbabwe", countryCapital: "Harare" },
];
